_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.10.7
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.10.7
            "5": 0.19.10
            "8":
                - 3
                - 5
            "12": 0.19.10
            "13": windows-amd64
decay_param:
    value: 0.001
dropout:
    value: 0
learn_rate:
    value: 0.01
